# Generated by Django 5.2 on 2025-05-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.FloatField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('kms_driven', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('is_sold', models.BooleanField(default=False)),
            ],
        ),
    ]
