# Generated by Django 4.1.13 on 2025-05-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='testdrive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='testdrive_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
