# Generated by Django 4.1.13 on 2025-05-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('orders', '0002_user_testdrive_date_user_testdrive_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='testdrive_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_drives', to='cars.car'),
        ),
    ]
